// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDy7xiKaxPka8vFR5gLiRUlI6lqxPqmFxk',
    appId: '1:801543949308:web:9b4bc3c789b23d92900079',
    messagingSenderId: '801543949308',
    projectId: 'quiz-app-b89f8',
    authDomain: 'quiz-app-b89f8.firebaseapp.com',
    storageBucket: 'quiz-app-b89f8.firebasestorage.app',
    measurementId: 'G-NQNWMGT916',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAs8dzzeBcsI6x4aMJF00zNumebIMUGMic',
    appId: '1:801543949308:android:3e2d418322167e3b900079',
    messagingSenderId: '801543949308',
    projectId: 'quiz-app-b89f8',
    storageBucket: 'quiz-app-b89f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQCCNgZC-cp7rAoseGPEguqSjD8Gkwjho',
    appId: '1:801543949308:ios:d120d7f112d0a721900079',
    messagingSenderId: '801543949308',
    projectId: 'quiz-app-b89f8',
    storageBucket: 'quiz-app-b89f8.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQCCNgZC-cp7rAoseGPEguqSjD8Gkwjho',
    appId: '1:801543949308:ios:d120d7f112d0a721900079',
    messagingSenderId: '801543949308',
    projectId: 'quiz-app-b89f8',
    storageBucket: 'quiz-app-b89f8.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDy7xiKaxPka8vFR5gLiRUlI6lqxPqmFxk',
    appId: '1:801543949308:web:cf2bbe8205c48979900079',
    messagingSenderId: '801543949308',
    projectId: 'quiz-app-b89f8',
    authDomain: 'quiz-app-b89f8.firebaseapp.com',
    storageBucket: 'quiz-app-b89f8.firebasestorage.app',
    measurementId: 'G-RVW0CR88LR',
  );
}
